inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Naming/AccessorMethodName:
  Exclude:
    - 'app/lib/dirk_diggler.rb'
    - 'app/models/movie.rb'
