QUOTES = [
  # The Big Lebowski
  'Walter Sobchak: Donny, shut the f- when do we play?',
  "Donny: Phone's ringing, Dude.",
  "The Dude: Fuck sympathy! I don't need your fuckin' sympathy, man, I need my fucking johnson!",
  "The Dude: God damn you Walter! You fuckin' asshole! Everything's a fuckin' travesty with you, man! And what was all that shit about Vietnam? What the FUCK, has anything got to do with Vietnam? What the fuck are you talking about?",
  "Walter Sobchak: You want a toe? I can get you a toe, believe me. There are ways, Dude. You don't wanna know about it, believe me.",
  "Walter Sobchak: Hell, I can get you a toe by 3 o'clock this afternoon... with nail polish. These fucking amateurs...",
  'Walter Sobchak: This is what happens when you fuck a stranger in the ass!',
  "The Dude: Obviously you're not a golfer.",
  "Walter Sobchak: Donny you're out of your element! Dude, the Chinaman is not the issue here!",
  "Walter Sobchak: Nihilists! Fuck me. I mean, say what you like about the tenets of National Socialism, Dude, at least it's an ethos.",
  "The Dude: She's not my special lady, she's my fucking lady friend. I'm just helping her conceive, man!",
  "The Dude: Where's the fucking money Lebowski?",
  'The Dude: That rug really tied the room together.',
  'The Dude: Who the fuck are the Knutsens?',
  "Walter Sobchak: You mark that frame an 8, and you're entering a world of pain.",
  'Walter Sobchak: Shut the fuck up, Donny.',
  "The Dude: Hey, careful, man, there's a beverage here!",
  'Walter Sobchak: Fucking dipshit with a nine toed woman.',
  "Walter Sobchak: Fuck it, Dude, let's go bowling.",
  'The Dude: Yeah, well. The Dude abides.',
  "Walter Sobchak: I told that Kraut a fuckin' thousand times, I don't roll on shabbos!",
  'Walter Sobchak: OVER THE LINE!',
  "Walter Sobchak: That's right, Dude, they peed on your fucking rug.",
  'Walter Sobchak: Look at our current situation with that camel fucker over in Iraq. Pacifism is not something to hide behind.',
  'The Dude: Mr. Treehorn treats objects like women, man.',
  'Walter Sobchak: Is this your homework, Larry? Is this your homework, Larry?',
  'Walter Sobchak: Look, Larry. Have you ever heard of Vietnam?',
  "Walter Sobchak: You're entering a world of pain, son. We know that this is your homework. We know that you stole a car.",
  'The Dude: H-hey, this is a private residence, man!',
  'The Dude: Ow! Fucking fascist!',
  "The Dude: Your money is being held by a kid named Larry Sellers. Real fucking brat, but I'm sure your goons can get it off him. I mean, he's fifteen.",
  "Walter Sobchak: You know, Dude, I myself dabbled in pacifism once. Not in 'Nam of course.",
  'The Dude: Does the Pope shit in the woods?',
  'The Dude: I! The Royal "we"! You know, the editorial...',
  'The Dude: Hmmm... Sure, that and a pair of testicles.',
  'Walter Sobchak: Am I wrong?',
  "The Dude: They're gonna kill that poor woman.",
  "The Dude: I hate the fuckin' Eagles man.",

  # Anchorman
  "Ron Burgundy: You're so wise. You're like a miniature Buddha, covered in hair.",
  'Ron Burgundy: I love scotch. Scotchy, scotch, scotch. Here it goes down, down into my belly...',
  "Ron Burgundy: I'm not a baby, I am a man. I am an anchorman.",
  "Ron Burgundy: I'm a man who discovered the wheel and built the Eiffel Tower out of metal and brawn. That's what kind of man I am. You're just a woman with a small brain. With a brain a third the size of us. It's science.",
  "Ron Burgundy: You've got a dirty whorish mouth.",
  'Ron Burgundy: Cannonball!',
  "Ron Burgundy: Sweet Lincoln's mullet.",
  'Ron Burgundy: I love poetry, and a glass of scotch, and, of course, my friend Baxter here.',
  "Ron Burgundy: I'M IN A GLASS CASE OF EMOTION",
  "Ron Burgundy: You know I don't speak Spanish.",
  "Ron Burgundy: I'm gonna punch you in the ovary, that's what I'm gonna do. A straight shot. Right to the babymaker",
  "Ron Burgundy: Great Odin's raven.",
  "Ron Burgundy: It's so damn hot... milk was a bad choice.",
  'Ron Burgundy: Son of a bee-sting.',
  "Ron Burgundy: I'm storming your castle on my steed, m'lady.",
  "Ron Burgundy: Oh, uh, it's the pleats... the pleats in the pants. It's an optical illusion. I was just about to take them back... to the pants store. Oh this is embarrassing.",
  'Ron Burgundy: How now brown cow.',
  'Ron Burgundy: Hey everyone! Come see how good I look!',
  'Ron Burgundy: The arsonist has oddly shaped feet.',
  "Ron Burgundy: And I'm Ron Burgundy. Go fuck yourself, San Diego.",

  # Dumb and Dumber
  "Lloyd: The first time I set eyes on Mary Swanson, I just got that old fashioned romantic feeling where I'd do anything to bone her.",
  "Harry: Just when I thought you couldn't possibly be any dumber, you go and do something like this... and totally redeem yourself!",
  'Lloyd: Man, you are one pathetic loser. No offense.',
  'Harry: I expected the Rocky Mountains to be a little rockier than this.',
  "Lloyd: I was thinking the same thing. That John Denver's full of shit, man.",
  "Lloyd: We got no food, no jobs... our PETS' HEADS ARE FALLING OFF!",
  'Lloyd: Mary... I desperately wanna make love to a school boy.',
  "Lloyd: That's a lovely accent you have. New Jersey?",
  "Lloyd: Austria! Well, then. G'day mate! Let's put another shrimp on the barbie!",
  'Lloyd: I got worms!',
  "Harry: Yeah I called her up. She gave me a bunch of crap about me not listening to her, or something. I don't know, I wasn't really paying attention.",
  "Lloyd: It's ok, I'm a limo driver!",
  'Lloyd: What do you think the chances are of a guy like you and a girl like me... ending up together?',
  "Harry: Oh, I don't know, Lloyd. The French are assholes.",
  'Harry: Nice set of hooters you got there!',
  'Lloyd: Hey guys. Woah, Big Gulps, huh? All right! Well, see ya later.',
  'Lloyd: I just figured she was a raging alcoholic.',
  'Lloyd: Why you going to the airport? Flying somewhere?',
  "Sea Bass' Friend: Kick his ass, Sea Bass!",
  "Harry: Anti-quitsies, you're it, quitsies, no anti-quitsies, no startsies!",
  "Harry: According to the map we've only gone about 4 inches.",
  "Harry: A tad? A tad, Lloyd? You drove almost a sixth of the way across the country in the wrong direction! Now we don't have enough money to get to Aspen, we don't have enough money to get home, we don't have enough money to eat, we don't have enough money to sleep!",
  "Lloyd: WE'VE LANDED ON THE MOON!",
  'Mental: Gas man. How the hell did they know that I got gas?',
  'Lloyd: Wanna hear the most annoying sound in the world?',
  'Lloyd: Tic-Tac, sir?',
  "Lloyd: We don't usually pick up hitchhikers... but I'm-a gonna go with my instincts on this one. Saddle up partner!",
  "Lloyd: I said, \"Do you love me?\" and she said, \"No, but that's a really nice ski mask.\"",
  "Lloyd: Thanks. Hey, I guess they're right. Senior citizens, although slow and dangerous behind the wheel, can still serve a purpose. I'll be right back. Don't you go dying on me!",
  'Harry: You sold my dead bird to a blind kid?',
  'Lloyd: Harry... your hands are freezing!',
  'Lloyd: Oh well here, take this extra pair of gloves, my hands are starting to get a little sweaty.',
  "Harry: Extra gloves? You've had this pair of extra gloves this whole time?",
  "Lloyd: You'll have to excuse my friend. He's a little slow. The town is back *that* way.",
  'Harry: Would you like an atomic pepper, Mr. Mentalino?',
  'Harry: Flush you bastard.',
  'Lloyd: Saw it in a movie once.',
  'Lloyd: No, in the movie, they catch up to him half mile down the road and slit his throat! Hahaha! It was a good one.',
  "Lloyd: Harry, you're alive... and a horrible shot!",
  "Lloyd: I got robbed by a sweet old lady on a motorized cart. I didn't even see it coming.",

  # American Psycho
  "Patrick Bateman: You're a fucking ugly bitch. I want to stab you to death, and then play around with your blood.",
  "Patrick Bateman: I like to dissect girls. Did you know I'm utterly insane?",
  'Patrick Bateman: I have to return some videotapes.',
  'Patrick Bateman: Well, for one thing, I think he was probably a closet homosexual who did a lot of cocaine. That whole Yale thing.',
  'Patrick Bateman: Do you like Huey Lewis and The News?',
  'Patrick Bateman: TRY GETTING A RESERVATION AT DORSIA NOW YOU FUCKING STUPID BASTARD! YOU, FUCKING BASTARD!',
  "Patrick Bateman: If you don't shut your fucking mouth, I will kill you.",
  "Patrick Bateman: There is a moment of sheer panic when I realize that Paul's apartment overlooks the park... and is obviously more expensive than mine.",
  "Patrick Bateman: I'm into, uh, well, murders and executions, mostly.",
  'Patrick Bateman: Your compliment was sufficient, Luis.',
  'Patrick Bateman: My need to engage in homicidal behaviour on a massive scale cannot be corrected but, uh, I have no other way to fulfill my needs.',
  "Patrick Bateman: No Luis. It's not me. You're mistaken."
]